version: "2"
services:
  lager-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    depends_on:
      - mongodb
    volumes:
      - .:/src
      - /node_modules
    ports:
     - 80:3000
    environment:
      - HOST=0.0.0.0
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    command: --smallfiles
    ports:
      - 27017:27017
